[package]
name = "ssh_sftp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ssh2 = "0.9.0"
rpassword = "7.2.0"
flutter_rust_bridge = "1"

[lib]
crate-type = ["staticlib", "cdylib"]